// GET CATEGORIES
const GET_CATEGORIES = 'categories/GET_CATEGORIES';
const GET_CATEGORIES_START = 'categories/GET_CATEGORIES_START';
const GET_CATEGORIES_STOP = 'categories/GET_CATEGORIES_STOP';
const GET_CATEGORIES_SUCCESS = 'categories/GET_CATEGORIES_SUCCESS';
const GET_CATEGORIES_FAIL = 'categories/GET_CATEGORIES_FAIL';

const types = {
  GET_CATEGORIES,
  GET_CATEGORIES_START,
  GET_CATEGORIES_STOP,
  GET_CATEGORIES_SUCCESS,
  GET_CATEGORIES_FAIL,
};

export default types;
